actions:
  - name: wave_pose_1
    enable: true
    hold_time: 1
    start: [
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03
  - name: wave_pose_2
    enable: true
    hold_time: 1
    start: [
      0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 2.96, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03
  - name: wave_pose_3
    enable: true
    hold_time: 1.1
    start: [
      0.0, 2.96, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03
  # - name: wave_pose_4
  #   enable: true
  #   start: [
  #     0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
  #   ]
  #   end: [
  #     0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
  #   ]
  #   step: 0.03

  - name: wave_pose_5
    enable: true
    start: [
      0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 0.0, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03

  - name: wave_pose_6
    enable: true
    hold_time: 1
    start: [
      0.0, 0.0, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03

  - name: temporary_pose_1
    enable: true
    hold_time: 1.5
    start: [
      0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 2.96, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03

  - name: temporary_pose_2
    enable: true
    hold_time: 1.5
    start: [
      0.0, 2.96, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 0.0, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03

  - name: wave_pose_7
    enable: true
    hold_time: 1.5
    start: [
      0.0, 0.0, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03

  - name: wave_pose_8
    enable: true
    hold_time: 2.5
    start: [
      0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 2.96, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03

  - name: wave_pose_9
    enable: true
    hold_time: 2.5
    start: [
      0.0, 2.96, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03

  - name: wave_pose_10
    enable: true
    hold_time: 2.5
    start: [
      0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 0.0, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03

  - name: wave_pose_11
    enable: true
    hold_time: 2.5
    start: [
      0.0, 0.0, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03

  # - name: wave_pose_v2_1
  #   enable: true
  #   # delay_time: 0.35
  #   hold_time: 1
  #   start: [
  #     0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
  #   ]
  #   end: [
  #     0.0, 0.0, -2.96, 0.0, 0.0, 0.0, 0.0,
  #   ]
  #   step: 0.03

  # - name: wave_pose_v2_2
  #   enable: true
  #   delay_time: 0.35
  #   start: [
  #     0.0, 0.0, -2.96, 0.0, 0.0, 0.0, 0.0,
  #   ]
  #   end: [
  #     0.0, 2.96, -2.96, 0.0, 0.0, 0.0, 0.0,
  #   ]
  #   step: 0.03

  # - name: wave_pose_v2_3
  #   enable: true
  #   delay_time: 0.35
  #   start: [
  #     0.0, 2.96, -2.96, 0.0, 0.0, 0.0, 0.0,
  #   ]
  #   end: [
  #     0.0, 0.0, -2.96, 0.0, 0.0, 0.0, 0.0,
  #   ]
  #   step: 0.03

  # - name: wave_pose_v2_4
  #   enable: true
  #   delay_time: 0.35
  #   start: [
  #     0.0, 0.0, -2.96, 0.0, 0.0, 0.0, 0.0,
  #   ]
  #   end: [
  #     0.0, 2.96, -2.96, 0.0, 0.0, 0.0, 0.0,
  #   ]
  #   step: 0.03

  # - name: wave_pose_v2_5
  #   enable: true
  #   delay_time: 0.35
  #   start: [
  #     0.0, 2.96, -2.96, 0.0, 0.0, 0.0, 0.0,
  #   ]
  #   end: [
  #     0.0, 0.0, -2.96, 0.0, 0.0, 0.0, 0.0,
  #   ]
  #   step: 0.03

  - name: home_pose
    enable: true
    start: [
      0.0, 1.57, -2.96, 0.0, 0.0, 0.0, 0.0,
    ]
    end: [
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    ]
    step: 0.03 