actions:
  - name: approach_pose_1
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.05
  - name: approach_pose_2
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.05
  - name: flower_pose_1
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.05
  - name: flower_pose_2
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.05
  - name: flower_pose_3
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.05
  - name: flower_pose_4
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.05
  - name: flower_pose_5
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.05
  - name: flower_pose_6
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.05
  - name: flower_pose_7
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.05
  - name: flower_pose_8
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.05
  - name: flower_pose_9
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.05
  - name: flower_pose_10
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.03
  - name: flower_pose_11
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.03
  - name: flower_pose_12
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.03
  - name: flower_pose_13
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.03
  - name: flower_pose_14
    enable: true
    start: [
      ,
    ]
    end: [
      ,
    ]
    step: 0.03
