actions:
  home:
    steps:
      - positions: [0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0]
        duration: 1.0
      - positions: [0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0]
        duration: 10.0

  wave:
    steps:
      - positions: [0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0]
        duration: 1.5
      - positions: [0.0, 2.09, -1.74, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 2.09, -1.74, 0.0, 0.0, 0.0, 0.0, 0.0]
        duration: 20.0

  wave2:
    steps:
      - positions: [0.0, 2.09, -1.74, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 2.09, -1.74, 0.0, 0.0, 0.0, 0.0, 0.0]
        duration: 2
      - positions: [0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 1.047, -0.78, 0.0, 0.0,0.0, 0.0, 0.0]
        duration: 30.0

  home2:
    steps:
      - positions: [0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 1.047, -0.78, 0.0, 0.0,0.0, 0.0, 0.0]
        duration: 2.0
      - positions: [0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0]
        duration: 40.0

  separate:
    steps:
      - positions: [0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0]
        duration: 2.0
      - positions: [0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0,0.0, 0.0, 0.0]
        duration: 20.0

  separate2:
    steps:
      - positions: [0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0,0.0, 0.0, 0.0]
        duration: 2.0
      - positions: [0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0]
        duration: 20.0

  separate3:
    steps:
      - positions: [0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0]
        duration: 2.0
      - positions: [0.0, 2.09, -1.74, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0]
        duration: 20.0

  separate4:
    steps:
      - positions: [0.0, 2.09, -1.74, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 1.047, -0.78, 0.0, 0.0, 0.0, 0.0, 0.0]
        duration: 2.0
      - positions: [0.0, 2.09, -1.74, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 2.09, -1.74, 0.0, 0.0, 0.0, 0.0, 0.0]
        duration: 20.0
