actions:
  # ======== 1. 初始姿态 ========
  - name: init_pose
    start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    end:   [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 1.2, -2.5, 0.0, -0.3, 0.0, 0.0, 0.0]
    step: 0.01

  # ======== 2. 左臂上摆 ========
  - name: wave_left_up
    start: [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 1.2, -2.5, 0.0, -0.3, 0.0, 0.0, 0.0]
    end:   [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 1.2, -2.5, 0.0, -0.3, 0.0, 0.0, 0.0]
    step: 0.01

  # ======== 3. 右臂上摆 ========
  - name: wave_right_up
    start: [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 1.2, -2.5, 0.0, -0.3, 0.0, 0.0, 0.0]
    end:   [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 2.0, -0.7, 0.0, -0.3, 0.0, 0.0, 0.0]
    step: 0.01

  # ======== 4. 左臂下摆 ========
  - name: wave_left_down
    start: [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 2.0, -0.7, 0.0, -0.3, 0.0, 0.0, 0.0]
    end:   [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 2.0, -0.7, 0.0, -0.3, 0.0, 0.0, 0.0]
    step: 0.01

  # ======== 5. 右臂下摆 ========
  - name: wave_right_down
    start: [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 2.0, -0.7, 0.0, -0.3, 0.0, 0.0, 0.0]
    end:   [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 1.2, -2.5, 0.0, -0.3, 0.0, 0.0, 0.0]
    step: 0.01

  # ======== 6. 往复循环 1 ========
  - name: wave_cycle_1
    start: [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 1.2, -2.5, 0.0, -0.3, 0.0, 0.0, 0.0]
    end:   [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 1.2, -2.5, 0.0, -0.3, 0.0, 0.0, 0.0]
    step: 0.01

  # ======== 7. 往复循环 2 ========
  - name: wave_cycle_2
    start: [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 1.2, -2.5, 0.0, -0.3, 0.0, 0.0, 0.0]
    end:   [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 2.0, -0.7, 0.0, -0.3, 0.0, 0.0, 0.0]
    step: 0.01

  # ======== 8. 往复循环 3 ========
  - name: wave_cycle_3
    start: [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 2.0, -0.7, 0.0, -0.3, 0.0, 0.0, 0.0]
    end:   [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 1.2, -2.5, 0.0, -0.3, 0.0, 0.0, 0.0]
    step: 0.01

  # ======== 9. 回到初始姿态 ========
  - name: final_rest
    start: [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            0.0, 1.2, -2.5, 0.0, -0.3, 0.0, 0.0, 0.0]
    end:   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    step: 0.01
