actions:
  # ======== 1. 初始姿态 ========
  - name: init_pose
    start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
    end:   [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    step:  0.03

  # ======== 2. 左臂上扬 ========
  - name: wave_up_left
    start: [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    end:   [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    step:  0.03

  # ======== 3. 右臂上扬 ========
  - name: wave_up_right
    start: [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    end:   [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    step:  0.03

  # ======== 4. 左臂上扬 ========
  - name: wave_cycle_1
    start: [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    end:   [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    step:  0.03

  # ======== 5. 右臂上扬 ========
  - name: wave_cycle_2
    start: [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]  
    end:   [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    step:  0.03

  # ======== 6. 左臂上扬 ========
  - name: wave_cycle_3
    start: [0.0, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    end:   [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    step:  0.03

  - name: wave_cycle_4
    start: [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    end:   [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    step:  0.03

  - name: home
    start: [0.0, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    end:   [0.0, 1.2, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    step:  0.03

  # ======== 7. 左右基座旋转 1.57 ========
  - name: base_rotate
    start: [0.0, 1.2, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    end:   [1.57, 1.2, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    step:  0.03

  # ======== 8. 继续往复运动（旋转后） ========
  - name: wave_cycle_5
    start: [1.57, 1.2, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    end:   [1.57, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    step:  0.03

  - name: wave_cycle_6
    start: [1.57, 1.2, -2.5, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    end:   [1.57, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    step:  0.03

  - name: wave_cycle_7
    start: [1.57, 2.0, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    end:   [1.57, 1.2, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    step:  0.03

  - name: final_rest
    start: [1.57, 1.2, -0.7, 0.0, 0.3, 0.0, 0.0, 0.0,
            ]
    end:   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            ]
    step: 0.05

  - name: vertical
    start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            ]
    end:   [0.0, 1.57, -1.57, 0.0, 0.0, 0.0, 0.0, 0.0,
            ]
    step: 0.05
  - name: vertical_1
    start: [0.0, 1.57, -1.57, 0.0, 0.0, 0.0, 0.0, 0.0,
            ]
    end:   [0.0, 1.05, -0.52, 0.0, 0.0, 0.0, 0.0, 0.0,
            ]
    step: 0.05

  - name: vertical_2
    start: [0.0, 1.05, -0.52, 0.0, 0.0, 0.0, 0.0, 0.0,
            ]
    end:   [1.57, 1.57, -1.57, 0.0, 0.0, 0.0, 0.0, 0.0,
            ]
    step: 0.05

  - name: vertical_3
    start: [1.57, 1.57, -1.57, 0.0, 0.0, 0.0, 0.0, 0.0,
            ]
    end:   [0.0, 1.57, -1.57, 0.0, 0.0, 0.0, 0.0, 0.0,
            ]
    step: 0.05

  - name: vertical_4
    start: [0.0, 1.57, -1.57, 0.0, 0.0, 0.0, 0.0, 0.0,
            ]
    end:   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            ]
    step: 0.05
